Add first_boot flag for page management and enable_watchdog flag for no boot watchdog
OpenVoiceOS/ovos-PHAL-plugin-wifi-setup pull request #8
Opened 2022-10-16 01:21 UTC by AIIX

- First boot flag will allow setting the mode select page as permanent on boot to solve the refresh bug
- Enable watchdog flag will keep the skip state in check to see if the user skipped setup and we don't then need to start watchdog service on every boot

@NeonDaniel please review as discussed in development chat

2022-10-17 17:44 UTC, NeonDaniel requested changes
Logic looks good, just suggesting a settings change

2022-10-17 17:44 UTC, NeonDaniel commented on ovos_PHAL_plugin_wifi_setup/__init__.py
> +        self.config_group = self.config.get("networking", {})
Do we need to put this in `networking`? This would make the core configuration:

```yaml
PHAL:
  ovos-PHAL-plugin-wifi-setup:
    networking:
      first_boot: True
      enabled_watchdog: True
```

This should probably just be `self.config.get('first_boot')`, etc.

2022-10-18 03:01 UTC, NeonDaniel commented
On first boot, the networking page still disappears/reappears every ~30s

2022-10-18 04:11 UTC, AIIX commented
> On first boot, the networking page still disappears/reappears every ~30s

Seems to be working for me on new image fine, also i didn't add any yml config file because first_boot is true by default on boot

2022-10-18 06:33 UTC, AIIX commented on ovos_PHAL_plugin_wifi_setup/__init__.py
> +        self.config_group = self.config.get("networking", {})
the reason to put this in networking group is because it adds these flags directly to mycroft.conf so won't first_boot will conflict with some other first_boot flag there ? if there is some other plugin that needs first_boot on and on wifi setup completion it sets it false globally then any other plugin needing it to be true will just fail, shouldn't all networking be put into a networking block to have it cleaner ?

2022-10-18 16:57 UTC, NeonDaniel commented on ovos_PHAL_plugin_wifi_setup/__init__.py
> +        self.config_group = self.config.get("networking", {})
`config` in this case is:
```yaml
PHAL:
  ovos-PHAL-plugin-wifi-setup:
```

2022-10-18 17:08 UTC, NeonDaniel commented
> > On first boot, the networking page still disappears/reappears every ~30s
> 
> Seems to be working for me on new image fine, also i didn't add any yml config file because first_boot is true by default on boot when there is wifi setup completed, and config is written to turn of first_boot only once the image connects to a network for the first time

Just looked again and I had installed this locally because my SSH session terminated...  working for me now, I only have the suggestions about config changes before merging

2022-10-18 17:56 UTC, JarbasAl commented on ovos_PHAL_plugin_wifi_setup/__init__.py
> +        self.first_boot = self.config_group.get("first_boot", True)
can first_boot be moved to a JsonStorageXDG? its session data not a config option
 
 enable_watchdog should remain in config, but i agree with @NeonDaniel that it should be `self.config.get("enable_watchdog", True)`, no need to add a "networking" section, this config is under the PHAL section and exclusive to the plugin, self.config_core should not be used here either

2022-10-18 17:57 UTC, JarbasAl requested changes
please remove "networking" section as discussed above and make things come directly from self.config, no need for nesting

also move first_boot to a JsonStorageXDG object. this is not a config settings, this is session data

2022-10-18 18:34 UTC, JarbasAl commented on ovos_PHAL_plugin_wifi_setup/__init__.py
> +        # - handle wifi setup later (previous skip button behavior)
@NeonDaniel i have this nitpick about design behavior

@AIIX could we make this distinction in the gui instead of a generic "Skip" button? Does the user want to run fully offline always, or just to do the setup later. And usually if we lose internet (eg, device moved location) we want setup to come back up, not disable the watchdog

2022-10-18 18:38 UTC, AIIX commented on ovos_PHAL_plugin_wifi_setup/__init__.py
> +        # - handle wifi setup later (previous skip button behavior)
what does the user ui button do exactly is what is to be figured out, once it skips setup all together, does the setup need to restart on boot, or only when user clicks the wifi button from drop down menu ? should watchdog completely be disabled when user skips or does watchdog run and never report any events if its in skipped mode ? what distinction do we mean here button label wise "skip setup" / "skip ... ? "

2022-10-18 18:42 UTC, AIIX commented on ovos_PHAL_plugin_wifi_setup/__init__.py
> +        # - handle wifi setup later (previous skip button behavior)
can the behaviour be explained better in gui terms here, what does skip button do and if not skip what else we need there ?

2022-10-18 18:47 UTC, NeonDaniel commented on ovos_PHAL_plugin_wifi_setup/__init__.py
> +        # - handle wifi setup later (previous skip button behavior)
Would it make sense to have another screen after 'skip' asking the user if they want to disable all online functionality or be asked again later? My inclination would be that if a user explicitly skips setup, disable the watchdog until/unless they manually connect to a wifi network only via the gui.

2022-10-18 18:52 UTC, AIIX commented on ovos_PHAL_plugin_wifi_setup/__init__.py
> +        # - handle wifi setup later (previous skip button behavior)
adding a second screen will break more things, maybe should be part of setup skill

2022-10-18 18:54 UTC, AIIX commented on ovos_PHAL_plugin_wifi_setup/__init__.py
> +        # - handle wifi setup later (previous skip button behavior)
at the worst if not that then it should be a popup menu if we need ask user explicitly what the next action should be, but not another page

2022-10-18 18:57 UTC, JarbasAl commented on ovos_PHAL_plugin_wifi_setup/__init__.py
> +        # - handle wifi setup later (previous skip button behavior)
i mean we should split skip button in 2 buttons GUI side, one of those buttons disables watchdog the other not

button 1 - run offline forever
button 2 - setup wifi later

2022-10-18 19:00 UTC, AIIX commented on ovos_PHAL_plugin_wifi_setup/__init__.py
> +        # - handle wifi setup later (previous skip button behavior)
somehow i still feel the skip button should define the exact intended behavior than we have more gui elements for this, what does skip exactly mean from all user perspectives ? generally it has always meant that user will initiate action to restart wifi setup if they want it, but it seems there are other ideas here

2022-10-18 19:08 UTC, JarbasAl commented on ovos_PHAL_plugin_wifi_setup/__init__.py
> +        # - handle wifi setup later (previous skip button behavior)
the design before was that setup should come back up everytime internet goes out and there is no wifi connection, thats what the watchdog does

lets see what scenarios we want to handle:
- device moved location, next boot should prompt wifi regardless of it being configured before
- user does not know wifi details, wants to test device, next boot should show setup again
- user does not ever want to connect the device to internet, watchdog should be disabled forever

i think the existing skip button handles 1 and 2, i am asking if we can add a new button for 3.

the changes daniel requested i believe also meant to solve 3

2022-10-18 19:17 UTC, AIIX commented on ovos_PHAL_plugin_wifi_setup/__init__.py
> +        # - handle wifi setup later (previous skip button behavior)
What do you want to display point 3 as is what I need, if there are two buttons on screen 1. Skip and 2.. ?

2022-10-18 19:22 UTC, JarbasAl commented on ovos_PHAL_plugin_wifi_setup/__init__.py
> +        # - handle wifi setup later (previous skip button behavior)
what sounds better?  "Connect Later"/"Skip" + "Never Connect"/"Run offline"

2022-10-19 11:10 UTC, AIIX commented
![add-offline-button](https://user-images.githubusercontent.com/19663666/196675143-9c1e4eda-9e8a-444b-96cb-d727bbb79675.png)

button, event and method added

2022-12-08 23:19 UTC, AIIX commented
Looks good to me

2022-12-08 23:22 UTC, NeonDaniel approved these changes

2022-12-09 00:55 UTC, JarbasAl commented on ovos_PHAL_plugin_wifi_setup/__init__.py
> +        self.plugin_setup_mode = 1
out of scope for this PR, but this should be made into a Enum later on

2022-12-09 00:55 UTC, JarbasAl approved these changes

2022-12-09 00:55 UTC, merged